### ISSUE TITLE
"Use Title Auto-Formatter" on tag field should not capitalize 'with'

### ISSUE THREAD

**Issue by thewebchameleon** [directus/format-title#50]
### Describe the Bug

When creating a new field, the tags type with the "Capitalization" option of "Use Title Auto-Formatter" is selected, it will capitalize "with". It should not capitalize "with" because it is a preposition like "and" and "a".

### To Reproduce

1. Create a new field of type `tags`, select the Capitalization dropdown option of "Use Title Auto-Formatter".
2. Add the item "chicken with chips and a draught"
3. It will capatalize "with", it should not capatalize "with" because it is a preposition like "and" and "a"
![image](https://github.com/directus/directus/assets/16325369/9864868d-ae01-47ed-a4b1-a559f90501e9)

### Directus Version

v10.x.x

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Heya! This library follows [APA style Title Casing](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case#:~:text=words%20of%20four%20letters%20or%20more%20(e.g.%2C%20%E2%80%9CWith%2C%E2%80%9D%20%E2%80%9CBetween%2C%E2%80%9D%20%E2%80%9CFrom%E2%80%9D)), which states (emphasis mine):

> How to implement title case
> In title case, capitalize the following words in a title or heading:
> 
> - the first word of the title or heading, even if it is a minor word such as “The” or “A”
> - the first word of a subtitlethe first word after a colon, em dash, or end punctuation in a heading
> - major words, including the second part of hyphenated major words (e.g., “Self-Report,” not “Self-report”)
> - **words of four letters or more (e.g., “With,” “Between,” “From”)**
> 
> Lowercase only minor words that are three letters or fewer in a title or heading (except the first word in a title or subtitle or the first word after a colon, em dash, or end punctuation in a heading):
> 
> - short conjunctions (e.g., “and,” “as,” “but,” “for,” “if,” “nor,” “or,” “so,” “yet”)
> - articles (“a,” “an,” “the”)
> - short prepositions (e.g., “as,” “at,” “by,” “for,” “in,” “of,” “off,” “on,” “per,” “to,” “up,” “via”)

So I believe `chicken with chips and a draught` should be capitalized to `Chicken With Chips and a Draught` 🙂

**Comment by rijkvanzanten** [comment]
What a perfect time to pull out a classic: _It's Not a Bug, It's a Feature._ 😄
